# Generated by Django 4.2.1 on 2023-07-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='expense',
            new_name='expenses',
        ),
    ]
